### ISSUE TITLE
Missing release date in <release>

### ISSUE THREAD

**Issue by jgarciao** [flathub/de.akaflieg_freiburg.cavok.add_hours_and_minutes#1]
Due to a [bug](https://github.com/flathub/linux-store-backend/issues/17) in flathub's webapp backend this app is not being shown in the website because the appstream information is not complete. If you look the file (/var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml) you will see that your app have the field `<release>` but there is no date informed for that release

```
<releases>
      <release version="0.9.6"/>
</releases>
```

The bug in the backend will be fixed next week but if you add a release date the app will appear in the store faster

**Comment by jgarciao** [comment]
We released the new version of the backend in production last Sunday and now the app appears in the website: https://flathub.org/apps/details/de.akaflieg_freiburg.cavok.add_hours_and_minutes

It would be fine if you could add the release date in the appdata file anyway

**Comment by kebekus** [comment]
@jgarciao Dear Jorge, I had forgotten to close this issue report.  The issue itself has been resolved long ago. Thank you for your help!
