### ISSUE TITLE
Update org.kde.Platform

### ISSUE THREAD

**Issue by Bohne13** [flathub/de.akaflieg_freiburg.cavok.add_hours_and_minutes#16]
Have tried updating the org.kde.Platform from 6.7 to 6.8 but the automated tests failed.

So here is the request per issue tracker to update the kde platform, like it was done recently in "Enroute Flight Navigation".

**Comment by kebekus** [comment]
Will do. Thanks for looking at my app!

**Comment by kebekus** [comment]
@Bohne13 Dear Jonas, thanks again for looking at this. I updated the platform as requested.
