### ISSUE TITLE
My Huawei 10 display is to small, can't see the whole content

### ISSUE THREAD

**Issue by Ralph-krh** [flathub/de.akaflieg_freiburg.cavok.add_hours_and_minutes#4]
My display on android Huawei 10 mobile phone is too small. I can't see the whole content. 
Enclose I sent you a file with the view I have.
Maybe you can adapt the view?

![Screenshot_20200209_092835_de akaflieg_freiburg enroute-1](https://user-images.githubusercontent.com/60840785/74099872-74e28a00-4b28-11ea-8e67-97720a212f7a.jpg)

**Comment by TingPing** [comment]
The bug tracker is here: https://gitlab.com/kebekus/addhoursandminutes/issues

This is only for packaging.
